# Generated by Django 3.0 on 2019-12-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.BigIntegerField(verbose_name='Booking Number')),
                ('customer_reference', models.CharField(blank=True, max_length=20, verbose_name='Customer Reference')),
                ('loading_port', models.CharField(blank=True, max_length=50, verbose_name='Loading Port')),
                ('vessel_departure', models.DateField()),
                ('vessel_name', models.CharField(blank=True, max_length=30)),
                ('discharge_port', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateField()),
                ('created_by', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
