# Generated by Django 3.0 on 2019-12-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='booking_number',
            field=models.BigIntegerField(unique=True, verbose_name='Booking Number'),
        ),
    ]
